defaults:
  - dataset: atp_ma_llm
  - model: qwen3_8B
  - _self_

run-name: ${model.model_name}-gen-dpo-ma
cuda_visible_devices: '7'
save_freq: 1
max_retries: 5

result_dir: ../results/ma_llm/dpo_train_data
temp_result_dir: ../tmp/test_results/${run-name}
max_workers: 6